-   id: git-secrets-scan
    name: "Git Secrets: scan files"
    description: Scans all files that are about to be committed.
    language: docker
    entry: git secrets --scan
    always_run: true
    pass_filenames: false
    stages: [commit]
