name: secrets scan

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: 'awslabs/git-secrets'
        ref: 'master'
    - name: Install git-secrets
      run: sudo make install
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install pipenv
      run: python -m pip install --upgrade pip && pip install pipenv
    - name: LS
      run: ls
    - name: Install deps
      run: git secrets --install
    - name: Install register
      run: git secrets --register-aws
    - name: Scan
      run: git secrets --scan
      
    
