name: secrets scan

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: 'awslabs/git-secrets'
        ref: 'master'
    - name: Install git-secrets
      run: make install
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install pipenv
      run: python -m pip install --upgrade pip && pip install pipenv
    - name: Install deps
      run: pipenv sync --system --dev
    - name: Run linter
      run: flake8 .
    - name: Check formatting
      run: black --check . && isort --check .
    - name: Check types
      run: mypy ./
